# Generated by Django 4.1.2 on 2023-10-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
