# Generated by Django 4.1.2 on 2023-10-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_delete_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('pic', models.ImageField(blank=True, default='', null=True, upload_to='uploads/')),
            ],
        ),
    ]
